package gg.swim.chunkdaddy.worker.document;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;
import com.hivemc.chunker.conversion.intermediate.level.ChunkerLevelSettings;
import com.hivemc.chunker.conversion.intermediate.level.annotations.Bedrock;
import com.hivemc.chunker.conversion.intermediate.level.annotations.Category;
import com.hivemc.chunker.conversion.intermediate.level.annotations.Hidden;
import com.hivemc.chunker.conversion.intermediate.level.annotations.Java;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * Describes {@link ChunkerLevelSettings} to the UI, and applies edits back to it safely.
 *
 * <p>The description is generated by reflection rather than written out by hand, so a field
 * added to Chunker at a later pinned revision appears in the panel on its own instead of
 * silently going missing. What is hand-written is only the presentation: which fields are
 * really enumerations rather than raw integers, what range a number is allowed to take, and
 * which fields this program decides for itself and will not let the user break.
 *
 * <p>Applying is written to be impossible to fail with. Every field is set independently,
 * out-of-range numbers are clamped rather than rejected, a value of the wrong shape is
 * refused by name, and nothing here throws. The worst outcome of a malformed request is that
 * some fields keep their previous value and the caller is told which ones did.
 */
public final class LevelSettingsSchema {
    /**
     * Fields this program owns.
     *
     * <p>{@code LevelName} is the export's world name, and {@code GeneratorType} has to stay
     * a void generator or Minecraft will generate terrain in and around the arenas. They are
     * shown so the user can see what the world will have, and refused on the way in.
     */
    private static final Set<String> LOCKED = Set.of("LevelName", "GeneratorType");

    /** Fields where an integer is really a named choice. Order is the numeric value. */
    private static final Map<String, List<String>> ENUMS = Map.of(
            "GameType", List.of("Survival", "Creative", "Adventure", "Spectator"),
            "Difficulty", List.of("Peaceful", "Easy", "Normal", "Hard"),
            "playerPermissionsLevel", List.of("Visitor", "Member", "Operator", "Custom"),
            "eduLevel", List.of("None", "Level 1", "Level 2", "Level 3"),
            "XBLBroadcastIntent", List.of("No multiplayer", "Invite only", "Friends only", "Friends of friends"),
            "FlatWorldVersion", List.of("Pre-1.18", "1.18 and later"));

    /** Inclusive numeric ranges, so a slider has somewhere sensible to go. */
    private static final Map<String, long[]> RANGES = Map.ofEntries(
            Map.entry("randomtickspeed", new long[]{0, 64}),
            Map.entry("serverChunkTickRange", new long[]{4, 32}),
            Map.entry("functioncommandlimit", new long[]{0, 1_000_000}),
            Map.entry("NetherScale", new long[]{1, 16}),
            Map.entry("SpawnX", new long[]{-30_000_000, 30_000_000}),
            Map.entry("SpawnY", new long[]{-64, 32_767}),
            Map.entry("SpawnZ", new long[]{-30_000_000, 30_000_000}),
            Map.entry("LimitedWorldOriginX", new long[]{-30_000_000, 30_000_000}),
            Map.entry("LimitedWorldOriginY", new long[]{-64, 32_767}),
            Map.entry("LimitedWorldOriginZ", new long[]{-30_000_000, 30_000_000}),
            Map.entry("rainTime", new long[]{0, 1_000_000}),
            Map.entry("lightningTime", new long[]{0, 1_000_000}),
            Map.entry("thunderTime", new long[]{0, 1_000_000}),
            Map.entry("clearWeatherTime", new long[]{0, 1_000_000}),
            Map.entry("rainLevel", new long[]{0, 1}),
            Map.entry("lightningLevel", new long[]{0, 1}),
            Map.entry("Time", new long[]{0, 1_000_000_000}),
            Map.entry("DayTime", new long[]{0, 24_000}));

    /** Notes shown under specific fields where the obvious reading is wrong. */
    private static final Map<String, String> HINTS = Map.of(
            "randomtickspeed", "0 stops random ticks only. Scheduled ticks, gravity, fluid flow "
                    + "and player-triggered updates still happen.",
            "commandsEnabled", "Required for command blocks and most behaviour-pack commands.",
            "experimentalgameplay", "Chunker's own flag. The source world's full experiments "
                    + "record, including Beta APIs, is carried across separately and is not "
                    + "controlled from here.",
            "GeneratorType", "Fixed to a void generator: ChunkDaddy writes every column in the "
                    + "export rectangle itself.",
            "LevelName", "Set from the world name given at export time.",
            "doimmediaterespawn", "Skips the death screen. Usually wanted on a duel world.",
            "showcoordinates", "Shows the coordinate readout on screen.");

    private LevelSettingsSchema() {
    }

    /** What an apply actually did. Rejections are named so the UI can explain itself. */
    public record ApplyResult(List<String> applied, List<String> rejected) {
    }

    // ------------------------------------------------------------------
    // Describing
    // ------------------------------------------------------------------

    /**
     * Describe the settings as categories of fields, each carrying its current value and
     * enough presentation detail for the panel to choose a control.
     */
    public static JsonObject describe(ChunkerLevelSettings settings) {
        Map<String, JsonArray> categories = new LinkedHashMap<>();
        // Fixed order, so the panel's tabs do not reshuffle between builds.
        for (Category.Type type : Category.Type.values()) {
            categories.put(type.getName(), new JsonArray());
        }

        for (Field field : ChunkerLevelSettings.class.getDeclaredFields()) {
            if (Modifier.isStatic(field.getModifiers()) || !Modifier.isPublic(field.getModifiers())) continue;
            if (field.isAnnotationPresent(Hidden.class)) continue;
            boolean bedrock = field.isAnnotationPresent(Bedrock.class);
            boolean java = field.isAnnotationPresent(Java.class);
            if (!bedrock && !java) continue;
            // ChunkDaddy only writes Bedrock worlds, so a Java-only field would be a control
            // that does nothing at all. Showing it would be a lie.
            if (!bedrock) continue;

            Object value;
            try {
                value = field.get(settings);
            } catch (Throwable e) {
                continue; // A field we cannot read is a field we cannot offer to edit.
            }

            Category category = field.getAnnotation(Category.class);
            String categoryName = (category == null ? Category.Type.UNKNOWN : category.value()).getName();

            JsonObject entry = new JsonObject();
            entry.addProperty("name", field.getName());
            entry.addProperty("label", label(field.getName()));
            entry.addProperty("locked", LOCKED.contains(field.getName()));
            entry.add("value", toJson(value));

            Class<?> type = field.getType();
            if (type == boolean.class || type == Boolean.class) {
                entry.addProperty("kind", "bool");
            } else if (type.isEnum()) {
                entry.addProperty("kind", "choice");
                JsonArray options = new JsonArray();
                for (Object constant : type.getEnumConstants()) {
                    options.add(String.valueOf(constant));
                }
                entry.add("options", options);
            } else if (ENUMS.containsKey(field.getName()) && isIntegral(type)) {
                entry.addProperty("kind", "choice");
                JsonArray options = new JsonArray();
                ENUMS.get(field.getName()).forEach(options::add);
                entry.add("options", options);
                entry.addProperty("optionsAreOrdinals", true);
            } else if (isIntegral(type)) {
                entry.addProperty("kind", "int");
                long[] range = RANGES.get(field.getName());
                if (range != null) {
                    entry.addProperty("min", range[0]);
                    entry.addProperty("max", range[1]);
                } else {
                    long[] natural = naturalRange(type);
                    entry.addProperty("min", natural[0]);
                    entry.addProperty("max", natural[1]);
                }
            } else if (type == float.class || type == double.class
                    || type == Float.class || type == Double.class) {
                entry.addProperty("kind", "real");
                long[] range = RANGES.get(field.getName());
                entry.addProperty("min", range != null ? range[0] : -1_000_000L);
                entry.addProperty("max", range != null ? range[1] : 1_000_000L);
            } else if (type == String.class) {
                entry.addProperty("kind", "text");
            } else {
                continue; // Anything else has no honest control; leave it alone entirely.
            }

            String hint = HINTS.get(field.getName());
            if (hint != null) entry.addProperty("hint", hint);
            categories.get(categoryName).add(entry);
        }

        JsonArray result = new JsonArray();
        for (Map.Entry<String, JsonArray> entry : categories.entrySet()) {
            if (entry.getValue().isEmpty()) continue;
            JsonObject group = new JsonObject();
            group.addProperty("name", entry.getKey());
            group.add("fields", entry.getValue());
            result.add(group);
        }
        JsonObject root = new JsonObject();
        root.add("categories", result);
        return root;
    }

    // ------------------------------------------------------------------
    // Applying
    // ------------------------------------------------------------------

    /**
     * Apply a flat map of field name to value onto the settings.
     *
     * <p>Fields are applied one at a time onto the live object; a value that cannot be used
     * leaves that field exactly as it was. Nothing here throws, and nothing here can leave a
     * field holding a value of the wrong type, so the settings object stays writable to NBT
     * whatever the caller sends.
     */
    public static ApplyResult apply(ChunkerLevelSettings settings, JsonObject values) {
        List<String> applied = new ArrayList<>();
        List<String> rejected = new ArrayList<>();
        if (values == null) return new ApplyResult(applied, rejected);

        for (Map.Entry<String, JsonElement> entry : values.entrySet()) {
            String name = entry.getKey();
            if (LOCKED.contains(name)) {
                rejected.add(name + " is set by ChunkDaddy and cannot be changed here");
                continue;
            }
            Field field;
            try {
                field = ChunkerLevelSettings.class.getDeclaredField(name);
            } catch (Throwable e) {
                rejected.add(name + " is not a setting this Chunker revision has");
                continue;
            }
            if (Modifier.isStatic(field.getModifiers()) || !Modifier.isPublic(field.getModifiers())
                    || field.isAnnotationPresent(Hidden.class)
                    || !field.isAnnotationPresent(Bedrock.class)) {
                rejected.add(name + " is not an editable Bedrock setting");
                continue;
            }
            JsonElement element = entry.getValue();
            if (element == null || element.isJsonNull() || !element.isJsonPrimitive()) {
                rejected.add(name + " was sent with a value that is not a single primitive");
                continue;
            }
            try {
                Object coerced = coerce(field, element.getAsJsonPrimitive(), name);
                field.set(settings, coerced);
                applied.add(name);
            } catch (Throwable e) {
                rejected.add(name + ": " + e.getMessage());
            }
        }
        return new ApplyResult(applied, rejected);
    }

    /**
     * Turn one JSON primitive into a value of the field's exact type.
     *
     * <p>Numbers are clamped to the field's advertised range rather than refused, so a
     * slider that is one off the end, or a UI built against a slightly different range, can
     * never write a value the game would choke on.
     */
    private static Object coerce(Field field, JsonPrimitive primitive, String name) {
        Class<?> type = field.getType();

        if (type == boolean.class || type == Boolean.class) {
            if (primitive.isBoolean()) return primitive.getAsBoolean();
            if (primitive.isNumber()) return primitive.getAsLong() != 0;
            String text = primitive.getAsString().trim().toLowerCase(Locale.ROOT);
            if (text.equals("true") || text.equals("1")) return Boolean.TRUE;
            if (text.equals("false") || text.equals("0")) return Boolean.FALSE;
            throw new IllegalArgumentException("expected true or false");
        }
        if (type == String.class) {
            return primitive.getAsString();
        }
        if (type.isEnum()) {
            String text = primitive.getAsString();
            for (Object constant : type.getEnumConstants()) {
                if (String.valueOf(constant).equalsIgnoreCase(text)) return constant;
            }
            throw new IllegalArgumentException("'" + text + "' is not one of its allowed values");
        }
        if (!primitive.isNumber() && !isNumericText(primitive)) {
            throw new IllegalArgumentException("expected a number");
        }

        if (type == float.class || type == Float.class || type == double.class || type == Double.class) {
            double value = primitive.getAsDouble();
            if (!Double.isFinite(value)) throw new IllegalArgumentException("must be a finite number");
            long[] range = RANGES.get(name);
            if (range != null) value = Math.max(range[0], Math.min(range[1], value));
            return (type == float.class || type == Float.class) ? (Object) (float) value : (Object) value;
        }

        long value = primitive.getAsLong();
        long[] range = RANGES.get(name);
        if (range != null) value = Math.max(range[0], Math.min(range[1], value));
        long[] natural = naturalRange(type);
        value = Math.max(natural[0], Math.min(natural[1], value));
        if (type == byte.class || type == Byte.class) return (byte) value;
        if (type == short.class || type == Short.class) return (short) value;
        if (type == int.class || type == Integer.class) return (int) value;
        if (type == long.class || type == Long.class) return value;
        throw new IllegalArgumentException("has a type this panel cannot edit");
    }

    private static boolean isNumericText(JsonPrimitive primitive) {
        if (!primitive.isString()) return false;
        try {
            Double.parseDouble(primitive.getAsString().trim());
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private static boolean isIntegral(Class<?> type) {
        return type == byte.class || type == Byte.class
                || type == short.class || type == Short.class
                || type == int.class || type == Integer.class
                || type == long.class || type == Long.class;
    }

    private static long[] naturalRange(Class<?> type) {
        if (type == byte.class || type == Byte.class) return new long[]{Byte.MIN_VALUE, Byte.MAX_VALUE};
        if (type == short.class || type == Short.class) return new long[]{Short.MIN_VALUE, Short.MAX_VALUE};
        if (type == int.class || type == Integer.class) return new long[]{Integer.MIN_VALUE, Integer.MAX_VALUE};
        return new long[]{Long.MIN_VALUE, Long.MAX_VALUE};
    }

    private static JsonElement toJson(Object value) {
        if (value == null) return com.google.gson.JsonNull.INSTANCE;
        if (value instanceof Boolean bool) return new JsonPrimitive(bool);
        if (value instanceof Number number) return new JsonPrimitive(number);
        if (value instanceof Enum<?> constant) return new JsonPrimitive(constant.name());
        return new JsonPrimitive(String.valueOf(value));
    }

    /** Turn a field name into something readable without renaming every field by hand. */
    private static String label(String name) {
        StringBuilder out = new StringBuilder(name.length() + 8);
        for (int index = 0; index < name.length(); index++) {
            char character = name.charAt(index);
            boolean boundary = index > 0
                    && Character.isUpperCase(character)
                    && (!Character.isUpperCase(name.charAt(index - 1))
                        || (index + 1 < name.length() && Character.isLowerCase(name.charAt(index + 1))));
            if (boundary) out.append(' ');
            out.append(index == 0 ? Character.toUpperCase(character) : character);
        }
        return out.toString();
    }
}
